// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://galothwqakokhuhpqlmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhbG90aHdxYWtva2h1aHBxbG1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjQwODAsImV4cCI6MjA2NTU0MDA4MH0.udrxFCSIKnWyEsvQovhPYBiDzO-q4r8UcQBm2j8CL9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});